# **************************************************************************
# *
# * Authors:     Grigory Sharov (gsharov@mrc-lmb.cam.ac.uk)
# *
# * MRC Laboratory of Molecular Biology (MRC-LMB)
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 3 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************

import math
from enum import Enum

import pyworkflow.protocol.params as params
from pyworkflow.constants import PROD
from pwem.protocols import ProtCreateMask3D
from pwem.objects import VolumeMask

import relion.convert as convert
from ..constants import MASK_AND


class outputs(Enum):
    outputMask = VolumeMask


class ProtRelionCreateMask3D(ProtCreateMask3D):
    """
    Creates three-dimensional solvent masks for cryo-EM volumes using
    RELION-based masking procedures. The protocol generates masks from a
    single reconstructed map or from logical comparisons between two
    independent volumes, allowing users to isolate biologically relevant
    density regions for downstream refinement, classification, and map
    interpretation.

    AI Generated:

    Create 3D Mask (ProtRelionCreateMask3D) — User Manual
        Overview

        The Create 3D Mask protocol produces volumetric masks that define
        which regions of a cryo-EM reconstruction should be considered
        signal and which regions should be treated as solvent or excluded
        background. In cryo-EM workflows, masking is a biologically
        important operation because it directly influences refinement
        stability, map sharpening, local resolution estimation, focused
        classification, and visualization quality.

        For biological users, masks are commonly used to isolate stable
        molecular regions, exclude noisy solvent areas, or focus analysis
        on specific domains or subcomplexes. Proper masking improves the
        interpretability of reconstructions and helps reduce artifacts
        caused by unrelated density or surrounding noise.

        Inputs and General Workflow

        The protocol accepts a reconstructed three-dimensional volume as
        the primary input. From this map, a binary mask is generated by
        identifying density values above a user-defined threshold. The mask
        is then expanded and smoothed to produce biologically meaningful
        boundaries suitable for downstream cryo-EM analysis.

        Optionally, a second volume may also be provided. In this mode,
        logical operations between the two maps can be used to define more
        selective masks. This approach is particularly useful when
        comparing conformational states, isolating flexible regions, or
        identifying structural differences between related
        reconstructions.

        Initial Lowpass Filtering

        Before mask generation, the protocol may apply a lowpass filter to
        the input map. This step suppresses high-frequency noise and
        emphasizes large-scale structural features that are more suitable
        for robust solvent mask generation.

        In biological practice, lowpass filtering is especially helpful
        when working with noisy maps or intermediate reconstructions. A
        moderate filter value often produces cleaner masks that better
        represent the molecular envelope while avoiding isolated noise
        peaks. Excessively aggressive filtering, however, may oversimplify
        the molecular shape and remove biologically meaningful protrusions
        or flexible regions.

        Threshold Selection

        Threshold selection is one of the most critical aspects of mask
        generation. The threshold determines which densities are considered
        part of the molecular structure and therefore included in the
        binary mask.

        Biologically meaningful thresholds should include all reliable
        structural density while excluding isolated solvent noise. If the
        threshold is too low, the mask may capture background artifacts or
        disconnected noise regions. If the threshold is too high, flexible
        domains or weakly resolved structural features may be excluded.

        In practice, users often inspect the reconstruction visually in a
        three-dimensional viewer before selecting the final threshold. This
        visual assessment is particularly important for heterogeneous
        complexes, membrane proteins, or assemblies containing flexible
        peripheral regions.

        Logical Comparison Between Volumes

        An advanced feature of the protocol allows mask generation through
        logical comparison of two independent volumes. This capability is
        useful for focused biological analysis where only specific shared
        or differential regions are of interest.

        Logical AND operations isolate regions present in both maps and are
        often useful for identifying conserved structural cores. Logical OR
        operations generate broader masks that encompass density present in
        either reconstruction, which may help preserve structural
        variability across states.

        Operations involving NOT conditions can isolate regions unique to
        one reconstruction or exclude density corresponding to another
        state. These strategies are particularly valuable when studying
        conformational transitions, ligand binding effects, or compositional
        heterogeneity.

        For reliable comparison, both input volumes should share the same
        voxel size and compatible spatial sampling. Differences in scaling
        or alignment may otherwise lead to biologically meaningless masks.

        Mask Expansion and Soft Edges

        After binarization, the mask can be expanded outward by a defined
        number of pixels. This extension step ensures that the molecular
        boundary is not artificially truncated and helps preserve signal
        near the edges of the reconstruction.

        The protocol also applies a soft edge around the final mask
        boundary. Soft edges are biologically and computationally important
        because abrupt transitions between masked and unmasked regions can
        introduce Fourier artifacts during refinement and postprocessing.

        In practical cryo-EM workflows, smooth mask edges generally improve
        stability and reduce ringing artifacts. Larger soft edges may be
        beneficial for flexible complexes, whereas smaller edges are often
        sufficient for compact and rigid particles.

        Inverted Masks

        The protocol optionally allows inversion of the final mask. In this
        mode, regions outside the original molecular envelope become
        selected instead of the molecular interior.

        Inverted masks are less common in routine cryo-EM refinement but
        can be useful for solvent analysis, artifact inspection, background
        characterization, or specialized processing workflows.

        Outputs and Their Interpretation

        The protocol produces a three-dimensional mask volume that can be
        used directly in downstream cryo-EM procedures. The resulting mask
        preserves the sampling properties of the original reconstruction and
        is suitable for refinement, focused classification, postprocessing,
        or visualization.

        Biologically, the quality of the mask strongly affects the quality
        of downstream interpretation. Well-designed masks improve signal
        isolation and structural clarity, whereas poorly designed masks may
        introduce artifacts, suppress meaningful flexibility, or bias
        refinement results.

        Practical Recommendations

        In routine cryo-EM practice, users should begin with conservative
        thresholds and visually inspect the resulting mask before applying
        it to refinement workflows. Ensuring that all biologically relevant
        regions remain enclosed is especially important for flexible or
        heterogeneous assemblies.

        Moderate mask extension combined with smooth soft edges generally
        provides robust results for most biological datasets. Very tight
        masks should be avoided unless there is a specific need for focused
        refinement of a highly localized structural region.

        When comparing multiple conformational states, logical masking
        operations can provide biologically meaningful ways to isolate
        conserved cores or structurally variable domains. However, careful
        interpretation is required to ensure that observed differences
        reflect genuine biological variation rather than masking artifacts.

        Final Perspective

        Three-dimensional masking is a central component of modern cryo-EM
        image processing because it defines the spatial regions that guide
        refinement and interpretation. Beyond its computational role,
        masking has direct biological implications by determining which
        structural features are emphasized, preserved, or excluded
        throughout downstream analysis. Careful mask design therefore
        remains essential for obtaining reliable and biologically meaningful
        cryo-EM results.
    """
    _label = 'create 3d mask'
    _devStatus = PROD
    _possibleOutputs = outputs

    # --------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        form.addSection(label='Mask generation')
        form.addParam('inputVolume', params.PointerParam,
                      pointerClass="Volume",
                      label="Input volume",
                      help="Select the volume that will be used to create the mask")
        form.addParam('initialLowPassFilterA', params.FloatParam,
                      default=15.,
                      label='Lowpass filter map by (A)',
                      help='Lowpass filter that will be applied to the input map, '
                           'prior to binarization. To calculate solvent masks, a '
                           'lowpass filter of 15-20A may work well.')
        # TODO: add wizard
        form.addParam('threshold', params.FloatParam, default=0.02,
                      label='Initial binarisation threshold',
                      help="This threshold is used to make an initial binary "
                           "mask from the average of the two unfiltered "
                           "half-reconstructions. If you don't know what "
                           "value to use, display one of the unfiltered "
                           "half-maps in a 3D surface rendering viewer and "
                           "find the lowest threshold that gives no noise "
                           "peaks outside the reconstruction.")

        form.addParam('doCompare', params.BooleanParam, default=False,
                      expertLevel=params.LEVEL_ADVANCED,
                      label='Compare with another volume to produce a mask?',
                      help='Logical comparison of two input volumes to produce a mask')

        form.addParam('inputVolume2', params.PointerParam,
                      pointerClass="Volume",
                      condition='doCompare',
                      expertLevel=params.LEVEL_ADVANCED,
                      label="Input volume (second)",
                      help="Select the volume that will be compared to the first one")

        form.addParam('operation', params.EnumParam, default=MASK_AND,
                      condition='doCompare',
                      expertLevel=params.LEVEL_ADVANCED,
                      label='Operation',
                      choices=['AND', 'OR', 'AND_NOT', 'OR_NOT'],
                      help='*AND*: Pixels in the initial mask will be one if the input '
                           'AND the second volume are above the threshold value.\n'
                           '*OR*: Pixels in the initial mask will be one if the input '
                           'OR the second volume are above the threshold value.\n'
                           '*AND_NOT*: pixels in the initial mask will be one if '
                           'the input is above the threshold AND the second volume '
                           'is below it.\n*OR_NOT*: pixels in the initial mask will be '
                           'one if the input is above the threshold OR the second '
                           'volume is below it.')

        form.addParam('extend', params.IntParam, default=3,
                      label='Extend binary mask by (px)',
                      help='The initial binary mask is extended this number of '
                           'pixels in all directions.')

        form.addParam('edge', params.IntParam, default=3,
                      label='Add a soft-edge (px)',
                      help='The extended binary mask is further extended with '
                           'a raised-cosine soft edge of the specified width.')

        form.addParam('doInvert', params.BooleanParam, default=False,
                      expertLevel=params.LEVEL_ADVANCED,
                      label='Invert final mask',
                      help='Invert the final mask')

        form.addParallelSection(threads=4, mpi=0)

    # --------------------------- INSERT steps functions ----------------------
    def _insertAllSteps(self):
        self.maskFile = self._getExtraPath('mask.mrc')
        self._insertFunctionStep(self.convertInputStep, self.inputVolume.get().getObjId(),
                                 needsGPU=False)
        self._insertFunctionStep(self.createMaskStep, needsGPU=False)
        self._insertFunctionStep(self.createOutputStep, needsGPU=False)
    
    # --------------------------- STEPS functions -----------------------------
    def convertInputStep(self, volId):
        self.inputVolFn = convert.convertBinaryVol(
            self.inputVolume.get(), self._getTmpPath())

        if self.doCompare:
            self.inputVol2Fn = convert.convertBinaryVol(
                self.inputVolume2.get(), self._getTmpPath())

    def createMaskStep(self):
        argsDict = {'--i ': self.inputVolFn,
                    '--ini_threshold ': self.threshold.get(),
                    '--extend_inimask ': self.extend.get(),
                    '--width_soft_edge ': self.edge.get(),
                    '--angpix ': self.inputVolume.get().getSamplingRate()
                    }
        if self.initialLowPassFilterA.get() != -1:
            argsDict['--lowpass '] = self.initialLowPassFilterA.get()

        args = ' --o %s ' % self.maskFile
        args += ' '.join(['%s %s' % (k, v) for k, v in argsDict.items()])

        if self.doCompare:
            op = self.operation.get()
            opStr = ['--and', '--or', '--and_not', '--or_not'][op]
            args += ' %s %s' % (opStr, self.inputVol2Fn)

        if self.doInvert:
            args += ' --invert'

        if self.numberOfThreads > 1:
            args += ' --j %d' % self.numberOfThreads

        self.runJob("relion_mask_create", args)

        return [self.maskFile]

    def createOutputStep(self):
        volMask = VolumeMask()
        volMask.setFileName(self.maskFile)
        volMask.setSamplingRate(self.inputVolume.get().getSamplingRate())

        self._defineOutputs(**{outputs.outputMask.name: volMask})
        self._defineSourceRelation(self.inputVolume, self.outputMask)
        
    # --------------------------- INFO functions ------------------------------
    def _validate(self):
        errors = []

        if self.doCompare:
            pixVol1 = self.inputVolume.get().getSamplingRate()
            pixVol2 = self.inputVolume2.get().getSamplingRate()

            if not math.isclose(pixVol1, pixVol2, abs_tol=0.001):
                errors.append('Pixel size should be the same for both input volumes.')

        return errors

    def _summary(self):
        messages = [
            "Created a mask from input volume using threshold *%0.5f*"
            % self.threshold.get(),
            "*Mask processing*",
            "   Extend by *%d* pixels" % self.extend,
            "   Apply soft edge of *%d* pixels" % self.edge]
        if self.doInvert:
            messages.append("   Inverted")

        return messages

    def _citations(self):
        return []

    def _methods(self):
        messages = [
            "*Mask creation*",
            "We processed the volume %s." % self.getObjectTag('inputVolume'),
            "We binarized it at threshold of %0.3f. " % self.threshold,
            "We extended binary mask by %d voxels." % self.extend,
            "And, we smoothed it by applying a soft edge of %d voxels."
            % self.edge.get()
        ]
        if self.doInvert:
            messages.append("We inverted the mask. ")
            messages.append("And, we smoothed it by applying a soft edge of "
                            "%d voxels." % self.edge)
        if self.hasAttribute('outputMask'):
            messages.append('We refer to the output mask as %s.'
                            % self.getObjectTag('outputMask'))

        return messages
